---
en:
  languageName: English
  languageCode: en-us
  weight: 1
  contentDir: content
  menus:
    main:
    - identifier: software
      name: Software
      title: Software
      url: "/#software"
      weight: 4
    - identifier: publications
      name: Publications
      title: Publications
      url: "/#publications"
      weight: 5
  params:
    terms:
      read: Read
      toc: Table of contents
      copyright: All rights reserved
      emailText: Check out this site
      datesFormat:
        article: Jan 2, 2006
        articleList: Jan 2, 2006
        articleRecent: Jan 2, 2006
