---
title: Rafael Barbedo
description: Hydrologist and geospatial data scientist working on hydrological modelling, environmental data systems, and flood forecasting.
favicon: "/fav.png"
useBootstrapCDN: false
mathjax: false
animate: true
theme:
  defaultTheme: light
  font:
    fontSize: 1rem
    fontWeight: 400
    lineHeight: 1.5
    textAlign: left
navbar:
  align: ms-auto
  brandName: Rafael Barbedo
  showBrandLogo: false
  disableSearch: false
  stickyNavBar:
    enable: true
    showOnScrollUp: true
  enableSeparator: false
  menus:
    disableAbout: false
    disableExperience: false
    disableEducation: true
    disableProjects: false
    disableAchievements: true
    disableContact: false
hero:
  enable: true
  bottomImage:
    enable: true
  button:
    enable: true
    download: true
    newPage: false
about:
  enable: true
  skills:
    enable: true
skills:
  enable: true
experience:
  enable: true
education:
  enable: true
  index: false
projects:
  enable: true
achievements:
  enable: true
contact:
  enable: true
footer:
  recentPosts:
    enable: false
  socialNetworks:
    github: https://github.com/gisflw
    linkedin: https://www.linkedin.com/in/rafael-barbedo/
listPages:
  disableFeaturedImage: false
singlePages:
  socialShare: true
  readTime:
    enable: true
    content: min read
  scrollprogress:
    enable: true
tags:
  openInNewTab: true
